trigger:
- production

pr: none

jobs:
- job: Build
  displayName: 'Build and Deploy'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
  
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.x'

  # Build .NET project
  - task: DotNetCoreCLI@2
    displayName: 'Build .NET Project'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration Release'

  # Build React application
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      cd ClientApp
      npm install
      npm run build
    displayName: 'Build React Application'

  # Publish artifacts
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/ClientApp/build'
      artifact: 'client-app'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/bin/Release'
      artifact: 'dotnet-app'
