services:
  simply-skip-app-staging:
    build:
      context: ./SimplySkip
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - postgres-staging
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ConnectionStrings__SSPostgresConnection: "Host=postgres-staging;Database=ssdb_staging;Username=johnz;Password=${DB_PASSWORD}"
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__DurationInMinutes: ${JWT_DURATION}
    env_file:
      - .env

  postgres-staging:
    image: postgres
    environment:
      POSTGRES_DB: ssdb_staging
      POSTGRES_USER: johnz
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db-data-staging:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin-staging:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5051:80"
    depends_on:
      - postgres-staging
    volumes:
      - pgadmin-data-staging:/var/lib/pgadmin
    env_file:
      - .env

volumes:
  db-data-staging:
  pgadmin-data-staging: