version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
      - image: node:latest

    steps:
      - checkout

      # Build .NET application
      - run:
          name: Build .NET Application
          command: dotnet build

      # Install Node.js dependencies for React frontend
      - run:
          name: Install Node.js Dependencies
          command: npm install
          working_directory: ./ClientApp

      # Build React frontend
      - run:
          name: Build React Frontend
          command: npm run build
          working_directory: ./ClientApp

  deploy:
    docker:
      - image: circleci/ssh:latest

    steps:
      - add_ssh_keys:
          fingerprints:
            - "${SSH_FINGERPRINT}"

      # Deploy to Linode VM
      - run:
          name: Deploy to Linode VM
          command: |
            ssh ${SSH_USER}@${SSH_HOST} "cd SimplySkip && git pull origin production && docker-compose up -d --build"
