name: Deploy to Staging

on:
  push:
    branches: [ staging ]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.203'

      - name: Restore dependencies
        run: dotnet restore ./SimplySkip.Tests

      - name: Run unit tests
        run: dotnet test ./SimplySkip.Tests
        continue-on-error: false

      - name: Setup SSH
        if: success()
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Git Config
        if: success()
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin git@github.com:${{ github.repository }}.git

      - name: Deploy to Linode Staging
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd SimplySkip-Staging
            git pull origin staging
            docker compose -f docker-compose.staging.yml down
            docker compose -f docker-compose.staging.yml up --build -d