name: Deploy to Dev

on:
  push:
    branches: [ dev ]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.203'

      - name: Run unit tests
        run: |
          dotnet restore ./SimplySkip.Tests
          dotnet test ./SimplySkip.Tests

      - name: Deploy to Linode Dev
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd SimplySkip-Dev
            git pull origin dev
            docker compose -f docker-compose.dev.yml down
            docker compose -f docker-compose.dev.yml up --build -d