name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to promote staging to production'
        required: true

jobs:
  deploy_production:
    if: github.event.inputs.confirm == 'yes'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Git Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Merge Staging to Main
        run: |
          git checkout staging
          git pull origin staging
          git checkout main
          git merge --no-ff staging
          git push origin main

      # Create a tag for this release for easy reference
      - name: Create Release Tag
        run: |
          RELEASE_TAG="release-$(date +%Y%m%d%H%M%S)"
          git tag $RELEASE_TAG
          git push origin $RELEASE_TAG

      # Deploy using the new script
      - name: Deploy to Linode Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Run the deployment script
            bash /root/deploy-production.sh