name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to promote dev to staging'
        required: true

jobs:
  deploy_staging:
    if: github.event.inputs.confirm == 'yes'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.203'

      - name: Run unit tests
        run: |
          dotnet restore ./SimplySkip.Tests
          dotnet test ./SimplySkip.Tests

      - name: Merge Dev to Staging
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout dev
          git pull origin dev
          git checkout staging
          git merge --no-ff dev
          git push origin staging

      - name: Deploy to Linode Staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd SimplySkip-Staging
            git pull origin staging
            docker compose -f docker-compose.staging.yml down
            docker compose -f docker-compose.staging.yml up --build -d