name: Deploy to Linode

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull latest Docker image
        run: docker-compose pull

      - name: Restart Docker containers
        run: docker-compose up -d
