name: Run Unit Tests and Deploy to Linode

on:
  push:
    branches:
      - main
      - production

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.203'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run unit tests
        run: dotnet test

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results

      - name: Fail if unit tests fail
        if: failure()
        run: exit 1

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH into Linode VM and deploy changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd SimplySkip
            git pull origin production
            docker compose down
            docker compose build
            docker compose up -d
