name: Rollback Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Specify version to roll back to (leave empty for previous version)'
        required: false
      confirm:
        description: 'Type "yes" to confirm rollback'
        required: true

jobs:
  rollback_production:
    if: github.event.inputs.confirm == 'yes'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute Rollback
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Run the rollback script
            bash /root/rollback-production.sh "${{ github.event.inputs.version }}"